#! /bin/bash

version=0.9.9-2

rm -rf deb
mkdir deb
mkdir deb/projekt7_$version
cp -R debian icons CMakeLists.txt COPYRIGHT main.cpp player.cpp player.h projekt7.desktop projekt7.svg projekt7ui.rc README deb/projekt7_$version
cd deb
tar -pczf projekt7_0.9.9.orig.tar.gz projekt7_$version
cd projekt7_$version
debuild -us -uc
